Made the Save method static to fix an error
The error I was getting is:
Assets/Modules/nvim-unity/Runtime/EditorLifeTime.cs(10,17): error
CS0120: An object reference is required for the non-static field,
method, or property 'NeovimEditor.Save()'